"""Tests for generic live and mock firmware build selection."""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from tools.build_firmware import (
    application_binary,
    discover_mock_adapters,
    release_package_command,
    write_build_selection,
)


class BuildFirmwareTests(unittest.TestCase):
    def test_discovers_every_specific_hardware_switch(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            kconfig = Path(directory) / "Kconfig.projbuild"
            kconfig.write_text(
                "config Z1_MOCK_ALL_HARDWARE\n"
                "config Z1_MOCK_SD_HARDWARE\n"
                "config Z1_MOCK_CAMERA_HARDWARE\n",
                encoding="utf-8",
            )

            self.assertEqual(
                discover_mock_adapters(kconfig),
                {
                    "camera": "CONFIG_Z1_MOCK_CAMERA_HARDWARE",
                    "sd": "CONFIG_Z1_MOCK_SD_HARDWARE",
                },
            )

    def test_selected_mock_explicitly_disables_every_other_adapter(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            adapters = {
                "camera": "CONFIG_Z1_MOCK_CAMERA_HARDWARE",
                "sd": "CONFIG_Z1_MOCK_SD_HARDWARE",
            }

            config, manifest = write_build_selection(
                output, adapters, {"sd"}, mock_all=False
            )

            self.assertEqual(
                config.read_text(encoding="utf-8"),
                "# Generated by tools/build_firmware.py; do not edit.\n"
                "# CONFIG_Z1_MOCK_ALL_HARDWARE is not set\n"
                "# CONFIG_Z1_MOCK_CAMERA_HARDWARE is not set\n"
                "CONFIG_Z1_MOCK_SD_HARDWARE=y\n",
            )
            self.assertEqual(
                json.loads(manifest.read_text(encoding="utf-8")),
                {
                    "available_mocks": ["camera", "sd"],
                    "mock_all": False,
                    "selected_mocks": ["sd"],
                },
            )

    def test_mock_all_and_live_are_unambiguous(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            adapters = {"sd": "CONFIG_Z1_MOCK_SD_HARDWARE"}

            all_config, _ = write_build_selection(
                output, adapters, set(), mock_all=True
            )
            self.assertIn(
                "CONFIG_Z1_MOCK_ALL_HARDWARE=y",
                all_config.read_text(encoding="utf-8"),
            )
            live_config, _ = write_build_selection(
                output, adapters, set(), mock_all=False
            )
            text = live_config.read_text(encoding="utf-8")
            self.assertIn("# CONFIG_Z1_MOCK_ALL_HARDWARE is not set", text)
            self.assertIn("# CONFIG_Z1_MOCK_SD_HARDWARE is not set", text)

    def test_project_kconfig_exposes_camera_and_sd_mocks(self) -> None:
        root = Path(__file__).resolve().parents[2]

        self.assertEqual(
            discover_mock_adapters(root / "main" / "Kconfig.projbuild"),
            {
                "camera": "CONFIG_Z1_MOCK_CAMERA_HARDWARE",
                "controller": "CONFIG_Z1_MOCK_CONTROLLER_HARDWARE",
                "sd": "CONFIG_Z1_MOCK_SD_HARDWARE",
            },
        )

    def test_release_uses_the_application_named_by_project_description(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            build = root / "custom-build"
            build.mkdir()
            (build / "project_description.json").write_text(
                json.dumps({"app_bin": "renamed-mainboard.bin"}),
                encoding="utf-8",
            )
            (build / "renamed-mainboard.bin").write_bytes(b"\xE9image")

            self.assertEqual(
                application_binary(build), (build / "renamed-mainboard.bin").resolve()
            )
            self.assertEqual(
                release_package_command(root, build, 0x010203)[-4:],
                [
                    "--mainboard-version",
                    "0x00010203",
                    "--output",
                    str(build / "firmware.bin"),
                ],
            )

    def test_release_rejects_application_paths_outside_the_build_tree(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            build = Path(directory)
            (build / "project_description.json").write_text(
                json.dumps({"app_bin": "../outside.bin"}), encoding="utf-8"
            )

            with self.assertRaisesRegex(ValueError, "inside the build directory"):
                application_binary(build)


if __name__ == "__main__":
    unittest.main()
