#!/usr/bin/env python3
"""Builds firmware with an explicit, arbitrary live/mock hardware selection."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Mapping, Sequence, Set, Tuple

MOCK_CONFIG_PATTERN = re.compile(r"^config Z1_MOCK_([A-Z0-9_]+)_HARDWARE$", re.MULTILINE)
GLOBAL_MOCK_CONFIG = "CONFIG_Z1_MOCK_ALL_HARDWARE"


def discover_mock_adapters(kconfig_path: Path) -> dict[str, str]:
    """Returns CLI names and Kconfig symbols for every specific mock adapter."""

    text = kconfig_path.read_text(encoding="utf-8")
    discovered: dict[str, str] = {}
    for match in MOCK_CONFIG_PATTERN.finditer(text):
        token = match.group(1)
        if token == "ALL":
            continue
        name = token.lower().replace("_", "-")
        discovered[name] = f"CONFIG_Z1_MOCK_{token}_HARDWARE"
    return dict(sorted(discovered.items()))


def _atomic_text(path: Path, content: str) -> None:
    """Replaces one generated text file without exposing a partial selection."""

    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def write_build_selection(
    build_directory: Path,
    adapters: Mapping[str, str],
    selected: Set[str],
    *,
    mock_all: bool,
) -> Tuple[Path, Path]:
    """Writes complete Kconfig selection and audit manifest into a build tree."""

    unknown = selected.difference(adapters)
    if unknown:
        raise ValueError(f"unknown mock adapter(s): {', '.join(sorted(unknown))}")
    build_directory.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by tools/build_firmware.py; do not edit."]
    lines.append(
        f"{GLOBAL_MOCK_CONFIG}=y"
        if mock_all
        else f"# {GLOBAL_MOCK_CONFIG} is not set"
    )
    for name, symbol in sorted(adapters.items()):
        lines.append(f"{symbol}=y" if name in selected else f"# {symbol} is not set")
    config_path = build_directory / "sdkconfig"
    _atomic_text(config_path, "\n".join(lines) + "\n")

    manifest_path = build_directory / "hardware-selection.json"
    manifest = {
        "available_mocks": sorted(adapters),
        "mock_all": mock_all,
        "selected_mocks": sorted(selected),
    }
    _atomic_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return config_path, manifest_path


def _mock_names(values: Sequence[str]) -> Set[str]:
    """Normalizes repeated and comma-separated mock adapter arguments."""

    return {
        name.strip().lower()
        for value in values
        for name in value.split(",")
        if name.strip()
    }


def _parser() -> argparse.ArgumentParser:
    """Creates the generic hardware-selection build command parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    selection = parser.add_mutually_exclusive_group(required=True)
    selection.add_argument(
        "--live", action="store_true", help="disable every mock adapter"
    )
    selection.add_argument(
        "--mock",
        action="append",
        metavar="NAME[,NAME...]",
        help="enable selected adapters; may be repeated",
    )
    selection.add_argument(
        "--mock-all", action="store_true", help="enable every implemented mock"
    )
    parser.add_argument(
        "-B",
        "--build-dir",
        type=Path,
        default=Path("build"),
        help="reusable generated build tree (default: build)",
    )
    parser.add_argument("--flash", action="store_true", help="flash after building")
    parser.add_argument("-p", "--port", help="serial port used with --flash")
    parser.add_argument(
        "--configure-only",
        action="store_true",
        help="write selection files without invoking ESP-IDF",
    )
    parser.add_argument(
        "--release",
        action="store_true",
        help="package a successful build as build/firmware.bin"    
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Generates one complete selection and invokes ESP-IDF in its build tree."""

    args = _parser().parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    adapters = discover_mock_adapters(root / "main" / "Kconfig.projbuild")
    selected = _mock_names(args.mock or [])
    try:
        config, manifest = write_build_selection(
            (root / args.build_dir).resolve(),
            adapters,
            selected,
            mock_all=args.mock_all,
        )
    except ValueError as error:
        print(error, file=sys.stderr)
        print(f"available mocks: {', '.join(adapters) or 'none'}", file=sys.stderr)
        return 2

    print(f"hardware selection: {manifest}")
    if args.configure_only:
        return 0
    if shutil.which("idf.py") is None:
        print("idf.py is unavailable; source the ESP-IDF export script", file=sys.stderr)
        return 2
    if args.port and not args.flash:
        print("--port requires --flash", file=sys.stderr)
        return 2

    command = [
        "idf.py",
        "-B",
        str(config.parent),
        "-D",
        f"SDKCONFIG={config}",
        "-D",
        f"SDKCONFIG_DEFAULTS={root / 'sdkconfig.defaults'}",
    ]

    if args.port:
        command.extend(["-p", args.port])

    command.append("flash" if args.flash else "build")

    build_result = subprocess.run(command, cwd=root, check=False)
    if build_result.returncode != 0:
        return build_result.returncode

    if not args.release:
        return 0

    build_directory = config.parent
    firmware_path = build_directory / "mainboard_firmware.bin"
    package_path = build_directory / "firmware.bin"

    if not firmware_path.is_file():
        print(
            f"expected firmware output was not created: {firmware_path}",
            file=sys.stderr,
        )
        return 1

    package_command = [
        sys.executable,
        str(root / "tools" / "package_firmware.py"),
        "--mainboard",
        str(firmware_path),
        "--output",
        str(package_path),
    ]

    package_result = subprocess.run(package_command, cwd=root, check=False)
    if package_result.returncode != 0:
        return package_result.returncode

    print()
    print("Release build completed successfully.")
    print()
    print("Built firmware:")
    print(f"  {firmware_path.relative_to(root)}")
    print()
    print("Built update package:")
    print(f"  {package_path.relative_to(root)}")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
