#!/usr/bin/env python3
"""Builds firmware with an explicit, arbitrary live/mock hardware selection."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Mapping, Sequence, Set, Tuple

MOCK_CONFIG_PATTERN = re.compile(r"^config Z1_MOCK_([A-Z0-9_]+)_HARDWARE$", re.MULTILINE)
GLOBAL_MOCK_CONFIG = "CONFIG_Z1_MOCK_ALL_HARDWARE"
DEFAULT_WEBUI_DIRECTORY = "webui"
ALTERNATE_WEBUI_DIRECTORY = "webui-alt"
SPEC_PARTITION_TABLE = "partitions.csv"
DEVELOPMENT_PARTITION_TABLE = "partitions-dev.csv"


def application_binary(build_directory: Path) -> Path:
    """Returns the generated application binary named by ESP-IDF metadata."""

    description_path = build_directory / "project_description.json"
    description = json.loads(description_path.read_text(encoding="utf-8"))
    relative = Path(description["app_bin"])
    candidate = (build_directory / relative).resolve()
    resolved_build = build_directory.resolve()
    if candidate.parent != resolved_build or not candidate.is_file():
        raise ValueError(
            "ESP-IDF application binary must exist directly inside the build directory"
        )
    return candidate


def release_package_command(
    root: Path, build_directory: Path, mainboard_version: int
) -> list[str]:
    """Builds the aggregate-packager invocation for one successful build."""

    firmware_path = application_binary(build_directory)
    return [
        sys.executable,
        str(root / "tools" / "package_firmware.py"),
        "--mainboard",
        str(firmware_path),
        "--mainboard-version",
        f"0x{mainboard_version:08X}",
        "--output",
        str(build_directory / "firmware.bin"),
    ]


def discover_mock_adapters(kconfig_path: Path) -> dict[str, str]:
    """Returns CLI names and Kconfig symbols for every specific mock adapter."""

    text = kconfig_path.read_text(encoding="utf-8")
    discovered: dict[str, str] = {}
    for match in MOCK_CONFIG_PATTERN.finditer(text):
        token = match.group(1)
        if token == "ALL":
            continue
        name = token.lower().replace("_", "-")
        discovered[name] = f"CONFIG_Z1_MOCK_{token}_HARDWARE"
    return dict(sorted(discovered.items()))


def select_webui_source(root: Path, alternate: bool) -> Path:
    """Returns a non-empty public or explicitly selected local Web UI tree."""

    directory_name = (
        ALTERNATE_WEBUI_DIRECTORY if alternate else DEFAULT_WEBUI_DIRECTORY
    )
    source = root / directory_name
    if not source.is_dir():
        raise ValueError(f"Web UI source directory does not exist: {source}")
    if not any(path.is_file() for path in source.rglob("*")):
        raise ValueError(f"Web UI source directory contains no files: {source}")
    return source.resolve()


def _atomic_text(path: Path, content: str) -> None:
    """Replaces one generated text file without exposing a partial selection."""

    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def write_build_selection(
    build_directory: Path,
    adapters: Mapping[str, str],
    selected: Set[str],
    *,
    mock_all: bool,
    release: bool = False,
    compact: bool = False,
    webui_source: str = DEFAULT_WEBUI_DIRECTORY,
    partition_table: str = SPEC_PARTITION_TABLE,
) -> Tuple[Path, Path]:
    """Writes complete Kconfig selection and audit manifest into a build tree."""

    unknown = selected.difference(adapters)
    if unknown:
        raise ValueError(f"unknown mock adapter(s): {', '.join(sorted(unknown))}")
    build_directory.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by tools/build_firmware.py; do not edit."]
    if compact and not release:
        raise ValueError("--compact requires --release")
    if release and (mock_all or selected):
        raise ValueError("--release requires --live; mock adapters are development-only")
    lines.append("CONFIG_COMPILER_OPTIMIZATION_SIZE=y" if release else "# CONFIG_COMPILER_OPTIMIZATION_SIZE is not set")
    # Release images keep warnings and errors, but omit informational log
    # strings and their call sites from components that honor ESP-IDF logging.
    lines.append("CONFIG_LOG_DEFAULT_LEVEL_WARN=y" if release else "# CONFIG_LOG_DEFAULT_LEVEL_WARN is not set")
    lines.append("CONFIG_LOG_DEFAULT_LEVEL=2" if release else "# CONFIG_LOG_DEFAULT_LEVEL is not set")
    lines.append(f'CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="{partition_table}"')
    lines.append("CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT=y" if compact else "# CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT is not set")
    lines.append("CONFIG_COMPILER_OPTIMIZATION_CHECKS_SILENT=y" if compact else "# CONFIG_COMPILER_OPTIMIZATION_CHECKS_SILENT is not set")
    lines.append("CONFIG_BT_STACK_NO_LOG=y" if compact else "# CONFIG_BT_STACK_NO_LOG is not set")
    lines.append("CONFIG_BOOTLOADER_LOG_LEVEL_WARN=y" if compact else "# CONFIG_BOOTLOADER_LOG_LEVEL_WARN is not set")
    # The attached sensor is identified as OV3660. Keep its driver and omit
    # unrelated esp32-camera sensor implementations from compact images.
    compact_camera_symbols = (
        "OV7670_SUPPORT", "OV7725_SUPPORT", "NT99141_SUPPORT", "OV2640_SUPPORT",
        "OV5640_SUPPORT", "GC2145_SUPPORT", "GC032A_SUPPORT", "GC0308_SUPPORT",
        "BF3005_SUPPORT", "BF20A6_SUPPORT", "SC030IOT_SUPPORT", "HM1055_SUPPORT",
        "HM0360_SUPPORT", "MEGA_CCM_SUPPORT",
    )
    for symbol in compact_camera_symbols:
        lines.append(
            f"# CONFIG_{symbol} is not set" if compact else f"CONFIG_{symbol}=y"
        )
    lines.append(
        f"{GLOBAL_MOCK_CONFIG}=y"
        if mock_all
        else f"# {GLOBAL_MOCK_CONFIG} is not set"
    )
    for name, symbol in sorted(adapters.items()):
        lines.append(f"{symbol}=y" if name in selected else f"# {symbol} is not set")
    config_path = build_directory / "sdkconfig"
    _atomic_text(config_path, "\n".join(lines) + "\n")

    manifest_path = build_directory / "hardware-selection.json"
    manifest = {
        "available_mocks": sorted(adapters),
        "mock_all": mock_all,
        "selected_mocks": sorted(selected),
        "webui_source": webui_source,
        "release": release,
        "compact": compact,
        "partition_table": partition_table,
    }
    _atomic_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return config_path, manifest_path


def _mock_names(values: Sequence[str]) -> Set[str]:
    """Normalizes repeated and comma-separated mock adapter arguments."""

    return {
        name.strip().lower()
        for value in values
        for name in value.split(",")
        if name.strip()
    }


def _parser() -> argparse.ArgumentParser:
    """Creates the generic hardware-selection build command parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    selection = parser.add_mutually_exclusive_group(required=True)
    selection.add_argument(
        "--live", action="store_true", help="disable every mock adapter"
    )
    selection.add_argument(
        "--mock",
        action="append",
        metavar="NAME[,NAME...]",
        help="enable selected adapters; may be repeated",
    )
    selection.add_argument(
        "--mock-all", action="store_true", help="enable every implemented mock"
    )
    parser.add_argument(
        "-B",
        "--build-dir",
        type=Path,
        default=Path("build"),
        help="reusable generated build tree (default: build)",
    )
    parser.add_argument("--flash", action="store_true", help="flash after building")
    parser.add_argument("-p", "--port", help="serial port used with --flash")
    parser.add_argument(
        "--configure-only",
        action="store_true",
        help="write selection files without invoking ESP-IDF",
    )
    parser.add_argument(
        "--release",
        action="store_true",
        help="package a successful build as BUILD_DIR/firmware.bin",
    )
    parser.add_argument(
        "--compact",
        action="store_true",
        help="enable additional size reductions; requires --release",
    )
    parser.add_argument(
        "--mainboard-version",
        type=lambda value: int(value, 0),
        default=0,
        help="unsigned 32-bit aggregate metadata used with --release",
    )
    parser.add_argument(
        "--alt_webui",
        "--alt-webui",
        dest="alt_webui",
        action="store_true",
        help="build SPIFFS from ignored local webui-alt instead of webui",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Generates one complete selection and invokes ESP-IDF in its build tree."""

    args = _parser().parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    adapters = discover_mock_adapters(root / "main" / "Kconfig.projbuild")
    selected = _mock_names(args.mock or [])
    try:
        webui_source = select_webui_source(root, args.alt_webui)
        config, manifest = write_build_selection(
            (root / args.build_dir).resolve(),
            adapters,
            selected,
            mock_all=args.mock_all,
            release=args.release,
            compact=args.compact,
            webui_source=webui_source.name,
            partition_table=SPEC_PARTITION_TABLE if args.release else DEVELOPMENT_PARTITION_TABLE,
        )
    except ValueError as error:
        print(error, file=sys.stderr)
        print(f"available mocks: {', '.join(adapters) or 'none'}", file=sys.stderr)
        return 2

    print(f"hardware selection: {manifest}")
    if args.configure_only:
        return 0
    if shutil.which("idf.py") is None:
        print(
            "idf.py is unavailable.\n\n"
            "Before running this command, activate the ESP-IDF environment:\n\n"
            "    source ~/esp/esp-idf/export.sh\n",
            file=sys.stderr,
        )
        return 2
    if args.port and not args.flash:
        print("--port requires --flash", file=sys.stderr)
        return 2
    if not args.release and args.mainboard_version != 0:
        print("--mainboard-version requires --release", file=sys.stderr)
        return 2
    if not 0 <= args.mainboard_version <= 0xFFFFFFFF:
        print("--mainboard-version must be an unsigned 32-bit value", file=sys.stderr)
        return 2

    command = [
        "idf.py",
        "-B",
        str(config.parent),
        "-D",
        f"SDKCONFIG={config}",
        "-D",
        f"SDKCONFIG_DEFAULTS={root / 'sdkconfig.defaults'}",
        "-D",
        f"Z1_WEBUI_DIR={webui_source}",
    ]

    if args.port:
        command.extend(["-p", args.port])

    command.append("flash" if args.flash else "build")

    build_result = subprocess.run(command, cwd=root, check=False)
    if build_result.returncode != 0:
        return build_result.returncode

    if not args.release:
        return 0

    build_directory = config.parent
    package_path = build_directory / "firmware.bin"
    try:
        firmware_path = application_binary(build_directory)
        package_command = release_package_command(
            root, build_directory, args.mainboard_version
        )
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"could not locate ESP-IDF application binary: {error}", file=sys.stderr)
        return 1

    package_result = subprocess.run(package_command, cwd=root, check=False)
    if package_result.returncode != 0:
        return package_result.returncode

    print()
    print("Release build completed successfully.")
    print()
    print("Built firmware:")
    print(f"  {firmware_path.relative_to(root)}")
    print()
    print("Built update package:")
    print(f"  {package_path.relative_to(root)}")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
